### ISSUE TITLE
Display in jupyter notebook

### ISSUE THREAD

**Issue by filipsPL** [kienerj/molecule-slide-generator#4]
Thanks for this piece of software!

Is there a way to use molecule-slide-generator to display resulting image directly in the jupyter notebook? So far I have to use this workaround: generate png as described, and later display it in the notebook:

```python
png = sg.generate_slide(mols, all_props)
from IPython.core.display import Image, display
display(Image(png))
```

**Comment by kienerj** [comment]
I did the same thing in my manual testing. I don't think an automated way exists but then I'm not a Jupyter expert. 

Only other option is to use the `out_path` option (save the image to disk) and then display it in the next cell as markdown cell with `![title](slide.png)`. But that isn't really any more convenient.

I suspect it works for rdkit molecules directly due to setting/manipulating the `__repr__` method accordingly.

**Comment by kienerj** [comment]
OK, this could be done by creating a simple subclass of bytes and returning that instead:

    class Slide(bytes):        
        def _repr_png_(self):
            return self

Then

    png = sg.generate_slide(mols, all_props)
    png

will display the image in Jupyter notebook while it can still be used as a bytes object.

But not sure if this is worth it or other possible downsides.

**Comment by filipsPL** [comment]
Good, thanks!
